//Get
GET http://localhost:3001 HTTP/1.1

###

// Mostrar pedidos:
GET http://localhost:3001/metodopagos HTTP/1.1
###

// Mostrar pedido por ID:
GET http://localhost:3001/metodopago/3 HTTP/1.1
###

// Mostrar pedido por Nombre:
GET http://localhost:3001/metodopagoNombre/Tarjeta HTTP/1.1
###

// INSERT por ID
POST http://localhost:3001/metodopago HTTP/1.1
Content-Type: application/json 
//Definimos el tipo de dato que vamos a enviar a la inserción que es de tipo JSON.

{
    "Nombre_Metodo": "Otros",
    "Tipo_Metodo_Pago": "Electronico",
    "Referencia": "132-456-789",
    "ID_Estado_FK": 0
}
###

// ACTUALIZAR por ID
PUT http://localhost:3001/metodopagoActualizar/5 HTTP/1.1
Content-Type: application/json 

{
    "ID_Metodo_Pago_PK": 5,
    "Nombre_Metodo": "Otrossss",
    "Tipo_Metodo_Pago": "Electronicosss",
    "Referencia": "132-456-789sss",
    "ID_Estado_FK": 1
}
###

// Eliminar por ID
DELETE http://localhost:3001/metodopagoEliminar/5 HTTP/1.1
###

// Mostrar ultimo id de la venta:
GET http://localhost:3001/pagoventa/ultimoidventa HTTP/1.1
###
