//Get
GET http://localhost:3001/vyf/productosparaventas HTTP/1.1
###

// Consulta productos por nombre en la venta
GET http://localhost:3001/vyf/buscarpornombreparaventas/Poker HTTP/1.1
###

// Consulta todos los deudores en la venta
GET http://localhost:3001/vyf/buscardeudorventa HTTP/1.1
###

// Consulta los deudores por ID en la venta
GET http://localhost:3001/vyf/buscariddeudorventa/3 HTTP/1.1
###

// Consulta los deudores por NOMBRE en la venta
GET http://localhost:3001/vyf/buscarnomdeudorventa/c HTTP/1.1
###

