//Get
GET http://localhost:3001 HTTP/1.1

###

// Mostrar productos:
GET http://localhost:3001/producto/Datos HTTP/1.1
###

// Mostrar producto por nombre:
GET http://localhost:3001/producto/BuscarDatoPorId/poker HTTP/1.1
###
